{"metadata":{"modules":[{"name":"Auth"}],"role":"collectionGroup","title":"Error Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Auth\/documentation\/Auth\/AuthError\/Error-Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/Auth\/documentation\/Auth","doc:\/\/Auth\/documentation\/Auth\/AuthError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/Auth\/documentation\/Auth\/AuthError\/localizedDescription"],"title":"Instance Properties","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth\/autherror\/error-implementations"]}],"sections":[],"references":{"doc://Auth/documentation/Auth/AuthError":{"title":"AuthError","url":"\/documentation\/auth\/autherror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/Auth\/documentation\/Auth\/AuthError","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Authentication error"}]},"doc://Auth/documentation/Auth":{"kind":"symbol","type":"topic","abstract":[],"title":"Auth","url":"\/documentation\/auth","role":"collection","identifier":"doc:\/\/Auth\/documentation\/Auth"},"doc://Auth/documentation/Auth/AuthError/localizedDescription":{"identifier":"doc:\/\/Auth\/documentation\/Auth\/AuthError\/localizedDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"localizedDescription","url":"\/documentation\/auth\/autherror\/localizeddescription","abstract":[],"role":"symbol"}}}